"""Build macro reference pages without importing or executing printer configuration.

Python standard library only. Run --write, --check, or --watch from any directory.
Unknown commands fail closed and need an explanation in annotations.json.
"""
from __future__ import annotations
import argparse
from dataclasses import dataclass
import glob
import hashlib
import html
import json
import os
from pathlib import Path
import re
import subprocess
import sys
import time
from urllib.parse import quote

TOOLS = Path(__file__).resolve().parent
DOCS = TOOLS.parent
CONFIG = DOCS.parent / 'config'
MARKER = '<!-- Generated by _tools/generate.py; edit annotations or config, not this page. -->'
HEADER = re.compile(r'^\[([^\]]+)\]')
OPTION = re.compile(r'^([a-zA-Z_][\w]*)(?:\s*[:=])\s*(.*)$')
BLOCK_KEYS = {'gcode', 'on_error_gcode', 'runout_gcode', 'insert_gcode', 'press_gcode', 'release_gcode'}
PRINTER_ENTRY = re.compile(r'printer-\d+\.cfg')


@dataclass
class Section:
    path: Path
    name: str
    rows: list

    @property
    def anchor(self):
        return re.sub(r'[^a-z0-9_-]+', '-', self.name.lower()).strip('-')

    @property
    def macro(self):
        return self.name.startswith(('gcode_macro ', 'delayed_gcode '))


def code(value):
    return '<code>' + html.escape(str(value)).replace('|', '&#124;') + '</code>'


def link(from_doc, target, anchor=''):
    return quote(Path(os.path.relpath(target, from_doc.parent)).as_posix(), safe='/._-') + ('#' + anchor if anchor else '')


def page(path):
    if PRINTER_ENTRY.fullmatch(path.name) and path.parent == CONFIG:
        return DOCS / 'printer-template.cfg.md'
    return DOCS / (path.relative_to(CONFIG).as_posix() + '.md')


def parse(path):
    sections = []
    current = None
    for n, line in enumerate(path.read_text(encoding='utf-8-sig').splitlines(), 1):
        match = HEADER.match(line)
        if match:
            current = Section(path, match[1], [])
            sections.append(current)
        if current:
            current.rows.append((n, line))
    # Separator comments and empty lines between sections are not macro actions.
    for section in sections:
        while section.rows and (not section.rows[-1][1].strip() or section.rows[-1][1].lstrip().startswith('#')):
            section.rows.pop()
    return sections


def config_files():
    return sorted(p for p in CONFIG.rglob('*') if p.is_file() and
                  (p.suffix in ('.cfg', '.conf') or p.name.endswith('.conf.backup')))


def entry_points(sections):
    """Return the canonical entry point, or every numbered fleet entry point."""
    canonical = CONFIG/'printer.cfg'
    if canonical in sections:
        return [canonical]
    fleet = sorted(path for path in sections if re.fullmatch(r'printer-\d+\.cfg', path.name))
    if fleet:
        return fleet
    raise ValueError('Missing config entry point: expected printer.cfg or printer-NN.cfg')


def active_tree(sections):
    active, edges = set(), []
    def walk(path, stack=()):
        if path in stack:
            raise ValueError('Recursive include: ' + str(path))
        if path in active:
            return
        if path not in sections:
            raise ValueError('Missing config: ' + str(path))
        active.add(path)
        for section in sections[path]:
            if section.name.startswith('include '):
                matches = sorted(path.parent.glob(section.name[8:]))
                if not matches and not glob.has_magic(section.name[8:]):
                    raise ValueError('Unresolved active include: ' + section.name)
                for child in matches:
                    if not child.resolve().is_relative_to(CONFIG.resolve()):
                        raise ValueError('Include escapes config tree: ' + str(child))
                    edges.append((path, child))
                    walk(child, stack + (path,))
    roots = entry_points(sections)
    for root in roots:
        walk(root)
    return active, edges, roots


def expression(text):
    """Translate common status/parameter syntax; preserve exact math when complex."""
    text = ' '.join(text.split()).strip()
    replacements = {
        'printer.pause_resume.is_paused': 'the printer is paused',
        'printer.extruder.can_extrude': 'the nozzle is hot enough to extrude',
        'printer.toolhead.homed_axes': 'the set of homed axes',
        'printer.print_stats.state': 'the print state',
        'printer.idle_timeout.state': 'the idle-timeout state',
        'printer.extruder.target': 'the nozzle temperature target',
        'printer.extruder.temperature': 'the measured nozzle temperature',
        'printer.configfile.settings': 'the loaded settings (including defaults)',
        'printer.configfile.config': 'the raw loaded settings',
        'printer.configfile': 'the loaded configuration and pending saves',
        'printer.toolhead.axis_maximum': 'the maximum axis positions',
        'printer.toolhead.axis_minimum': 'the minimum axis positions',
        'printer.gcode_move.gcode_position': 'the current G-code position',
        'printer.gcode_move.homing_origin': 'the coordinate offsets',
        'printer.gcode_move.absolute_coordinates': 'XYZ uses absolute coordinates',
        'printer.gcode_move.absolute_extrude': 'E uses absolute coordinates',
        'printer.gcode_move.speed_factor': 'the feed-rate multiplier',
        'printer.gcode_move.extrude_factor': 'the extrusion multiplier',
        'printer.toolhead.extruder': 'the active extruder name',
        'menu.input': 'the value selected on the LCD',
        'rawparams': 'all original command arguments',
    }
    for old, new in replacements.items():
        text = text.replace(old, new)
    text = re.sub(r"printer\[['\"]gcode_macro ([^'\"]+)['\"]\]", r'the stored state of \1', text)
    text = re.sub(r'params\.([A-Z_]+)', r'the supplied \1 argument', text)
    text = re.sub(r'\|default\(([^()]*)\)', r' (use \1 if absent)', text)
    for old, new in [('|float', ' as a decimal'), ('|int', ' as an integer'),
                     ('|abs', ' as a positive magnitude'), ('|lower', ' in lowercase'),
                     ('|upper', ' in uppercase'), ('|string', ' as text'),
                     ('==', ' equals '), ('!=', ' differs from '),
                     ('>=', ' is at least '), ('<=', ' is at most ')]:
        text = text.replace(old, new)
    return text


class Builder:
    def __init__(self):
        self.annotations = json.loads((TOOLS/'annotations.json').read_text(encoding='utf-8'))
        self.files = config_files()
        self.sections = {p: parse(p) for p in self.files}
        self.active, self.edges, self.entry_points = active_tree(self.sections)
        self.targets = {}
        self.aliases = {}
        self.unknown = []
        self.row_count = 0
        for path, sections in self.sections.items():
            for s in sections:
                if s.macro:
                    self.targets.setdefault(s.name.split(' ', 1)[1].upper(), []).append(s)
                for _, line in s.rows:
                    if line.startswith('rename_existing:'):
                        self.aliases[line.split(':',1)[1].strip().upper()] = s

    def refs(self, text, source):
        """Potential calls/state references, including hooks and delayed IDs.

        Names in literal messages/comments do not constitute execution evidence.
        Caller lists explicitly label these as references.
        """
        clean = '\n'.join(l.split('#',1)[0].split(';',1)[0] for l in text.splitlines())
        names = set(re.findall(r'(?m)^\s*(?:gcode:\s*)?([A-Za-z_][A-Za-z_0-9]*)(?=\s|$)', clean))
        names.update(re.findall(r'%\}\s*([A-Za-z_][A-Za-z_0-9]*)', clean))
        names.update(re.findall(r"gcode_macro ([A-Za-z_][A-Za-z_0-9]*)['\"]",clean))
        names.update(re.findall(r'\b(?:MACRO|ID)=([A-Za-z_][A-Za-z_0-9]*)', clean))
        names.update(re.findall(r"(?m)^variable_user_\w+:\s*['\"]([A-Za-z_][A-Za-z_0-9]*)",clean))
        names = {n.upper() for n in names}
        result = []
        for name in sorted(names & self.targets.keys()):
            choices = self.targets[name]
            target = next((s for s in choices if s.path in self.active), choices[0])
            if target is source:
                continue
            result.append((name, target))
        # Runtime calls can select a different name through a hook or saved dict.
        for key, names in self.annotations.get('dynamic_calls', {}).items():
            if key in clean:
                for name in names:
                    if name in self.targets:
                        target = self.targets[name][0]
                        if target is not source and (name,target) not in result:
                            result.append((name,target))
        return result

    def ref_link(self, source_page, name, target):
        return f'[{name}]({link(source_page, page(target.path), target.anchor)})'

    def command(self, text, source, doc):
        text = text.strip()
        if not text:
            return ''
        if text.startswith(('#',';')):
            return 'Trailing comment; not executed.'
        if text.startswith('G9{'):
            return 'Choose G90 (absolute XYZ) when ABSOLUTE is true, otherwise G91 (relative XYZ).'
        if text.startswith('M8{'):
            return 'Choose M82 (absolute E) when ABSOLUTE_E is true, otherwise M83 (relative E).'
        m = re.match(r'([A-Za-z_][\w]*)\b(.*)', text, re.S)
        if not m:
            if text.startswith('{'):
                if 'action_raise_error' in text:
                    return 'Stop this macro and its callers during template evaluation; report the shown error message.'
                if 'action_respond_info' in text:
                    return 'Write the shown message to the console during template evaluation; this is not a movement.'
                if 'action_call_remote_method' in text:
                    return 'Ask the connected service (normally Moonraker) to run the named remote operation during template evaluation.'
                if 'menu.exit()' in text:
                    return 'Exit the LCD menu.'
                if 'menu.back()' in text:
                    return 'Return to the previous LCD menu.'
                return 'Emit a command selected at runtime from ' + code(text) + '; see the linked state/hook owners below. The resolved command determines the action.'
            self.unknown.append(f'{source.path.name}: {text}')
            return 'Explanation required.'
        cmd, args = m[1].upper(), m[2].strip()
        if cmd in self.targets:
            choices = self.targets[cmd]
            target = next((s for s in choices if s.path in self.active), choices[0])
            suffix = ' Forward ' + code(args) + '.' if args else ' Use its default arguments.'
            return 'Run ' + self.ref_link(doc,cmd,target) + ', which is evaluated separately when reached.' + suffix
        if cmd in self.aliases:
            owner = self.aliases[cmd]
            return 'Call the original command saved by ' + self.ref_link(doc,owner.name.split(' ',1)[1],owner) + '; bypass that macro wrapper.'
        if cmd in ('G0', 'G1'):
            words = re.findall(r'([XYZEFxyzef])\s*([+-]?\{.*?\}|[+-]?[\d.]+)', args)
            parts = []
            for axis, val in words:
                axis = axis.upper()
                if axis == 'F':
                    try: desc = f'{float(val)/60:g} mm/s ({val} mm/min)'
                    except ValueError: desc = code(val) + ' mm/min'
                    parts.append('use feed rate ' + desc)
                elif axis == 'E':
                    parts.append('command filament E=' + code(val) + ' mm; in relative E mode negative retracts and positive feeds')
                else:
                    parts.append('command ' + axis + '=' + code(val) + ' mm')
            return ('; '.join(parts) or 'Move using the runtime coordinates shown') + '. XYZ follows G90/G91; E follows G91/M82/M83. Omitted axes and feed rate retain their previous values.'
        if cmd in ('M104','M109','M140','M190'):
            temp = args[args.find('S')+1:] if 'S' in args else args
            heater = 'bed' if cmd in ('M140','M190') else 'nozzle'
            wait = ' Wait for the requested temperature.' if cmd in ('M109','M190') else ' Continue without waiting for temperature.'
            return 'Set the ' + heater + ' target using ' + code(temp) + ' °C; zero turns its heater off.' + wait
        if cmd == 'G28':
            return 'Home ' + (code(args) if args else 'all axes') + ' using the native homing path. Here safe_z_home handles Z positioning; this is not a standalone tap command.'
        if cmd == 'G4':
            return 'Wait for ' + code(args) + ' (P is milliseconds; 1000 ms = 1 second).'
        if cmd == 'SET_GCODE_VARIABLE':
            var = re.search(r'VARIABLE=(\w+)', args)
            val = args.split('VALUE=',1)[-1]
            return 'Store ' + code(val) + ' in the named macro\'s ' + code(var[1] if var else 'selected') + ' variable for later calls. This changes runtime state, not the config file.'
        if cmd == 'SET_STEPPER_ENABLE':
            return 'Enable holding/drive power for the selected motor.' if 'ENABLE=1' in args else 'Release the selected motor so it can be turned manually; this does not disable the other motors.'
        if cmd == 'UPDATE_DELAYED_GCODE':
            return 'Cancel the named delayed callback.' if re.search(r'DURATION=0(?:\.0)?(?:\s|$)',args) else 'Schedule the named delayed callback after the DURATION value in seconds; scheduling is not an immediate call.'
        if cmd == 'RESTORE_GCODE_STATE':
            return 'Restore the saved coordinate modes, E accounting, offsets and feed settings.' + (' Also move back to the saved XYZ position.' if 'MOVE=1' in args else ' Do not move back to the saved XYZ position (MOVE defaults to 0).')
        descriptions = self.annotations['commands']
        if cmd in descriptions:
            return descriptions[cmd]
        self.unknown.append(f'{source.path.relative_to(CONFIG)}: {text}')
        return 'Explanation required for ' + code(cmd) + '.'

    def explain(self, text, source, doc, block):
        stripped = text.strip()
        if not stripped:
            return 'Blank separator; no action.'
        if stripped.startswith(('#',';')):
            return 'Comment only; Klipper does not execute this line.'
        if HEADER.match(text):
            return 'Declare this ' + ('callable macro' if source.name.startswith('gcode_macro ') else 'configuration section') + '.'
        override = self.annotations.get('lines', {}).get(stripped)
        if override:
            return override
        option = OPTION.match(text)
        if option:
            key, val = option.groups()
            if key in BLOCK_KEYS:
                return 'Begin the command template.' + (' ' + self.command(val,source,doc) if val else ' The following indented lines belong to it.')
            if key.startswith('variable_'):
                meaning = self.annotations.get('variables',{}).get(key[9:], key[9:].replace('_',' '))
                return 'Initialize ' + code(key[9:]) + ' (' + meaning + ') to ' + code(val) + ' at restart; later calls may change it.'
            if key == 'rename_existing':
                return 'Keep the original command under ' + code(val) + ' so this wrapper can call it without recursing.'
            meanings = {'description':'Set the help text', 'name':'Set the LCD label', 'type':'Select the LCD item type (disabled hides the item)',
                        'enable':'Show/enable this LCD item only when this expression is true', 'input':'Read the current editable LCD value',
                        'input_min':'Set the minimum editable value', 'input_max':'Set the maximum editable value',
                        'input_step':'Set the amount changed per encoder step', 'index':'Set the item ordering',
                        'realtime':'Choose whether editing immediately applies changes', 'initial_duration':'Set the first delayed execution time in seconds after startup'}
            return meanings.get(key, 'Set the '+key.replace('_',' ')+' option') + ': ' + code(expression(val)) + '.'
        if block == 'continuation':
            return 'Continue the expression or value started above: ' + code(expression(stripped)) + '. This is not a separate G-code command.'
        if '{%' in stripped and '%}' not in stripped:
            return 'Begin a multi-line template expression: ' + code(expression(stripped[2:])) + '. Its continuation lines complete the same expression before any commands execute.'
        if '{%' in stripped:
            parts = re.split(r'(\{%.*?%\})', stripped)
            result = []
            for part in parts:
                if not part.strip():
                    continue
                if part.startswith('{%'):
                    content = part[2:-2].strip()
                    if content.startswith('set '):
                        var, _, value = content[4:].partition('=')
                        if '.append(' in value:
                            result.append('Append the shown item to the message list; _dummy only receives the operation\'s return value.')
                        elif '.update(' in value:
                            result.append('Update the named entries in the referenced settings dictionary during template evaluation.')
                        else:
                            result.append('Calculate local '+code(var.strip())+' from '+code(expression(value))+'. It lasts for this evaluation only.')
                    elif content.startswith(('if ', 'elif ')):
                        result.append(('Start a conditional branch: ' if content.startswith('if ') else 'Otherwise test: ') + code(expression(content.split(' ',1)[1])) + '. Only a true branch emits its commands.')
                    elif content == 'else': result.append('Otherwise use this branch.')
                    elif content == 'endif': result.append('End this conditional block.')
                    elif content.startswith('for '): result.append('Repeat for each ' + code(expression(content[4:])) + '.')
                    elif content == 'endfor': result.append('End the repeated block.')
                    else:
                        self.unknown.append('Template directive: '+content)
                        result.append('Explanation required.')
                else:
                    result.append(self.command(part,source,doc))
            # A multi-line template starts here and is explained as one expression.
            if '%}' not in stripped:
                return 'Begin a multi-line template expression: ' + code(expression(stripped[2:])) + '. Its continuation lines complete the same expression before any commands execute.'
            return ' '.join(result)
        if block == 'continuation':
            return 'Continue the expression or value started above: ' + code(expression(stripped)) + '. This is not a separate G-code command.'
        return self.command(stripped.split(';',1)[0].split('#',1)[0],source,doc)

    def build(self):
        outputs = {}
        macro_count = 0
        for path, sections in self.sections.items():
            if PRINTER_ENTRY.fullmatch(path.name) and path.parent == CONFIG:
                continue
            doc = page(path)
            rel = path.relative_to(CONFIG).as_posix()
            status = 'Active in a configured printer entry-point include tree.' if path in self.active else (
                'Archived backup; not active in a printer entry-point include tree.' if 'backups' in path.parts else
                'Service configuration, loaded separately from Klipper.' if path.suffix == '.conf' else
                'Not included by a printer entry point; optional configuration or saved runtime data.')
            lines = [MARKER, '# '+rel, '', status, '',
                     '[Source file]('+link(doc,path)+') · [All files]('+link(doc,DOCS/'README.md')+') · [Reading guide]('+link(doc,DOCS/'READING_GUIDE.md')+')', '',
                     'Source text SHA256 (LF-normalized): `'+hashlib.sha256(path.read_text(encoding='utf-8-sig').encode()).hexdigest()+'`.', '']
            commented = re.findall(r'^\s*#\s*\[(gcode_macro [^\]]+|delayed_gcode [^\]]+)\]',path.read_text(encoding='utf-8-sig'),re.M)
            if commented:
                lines += ['Commented examples (not loaded): '+', '.join(code(n) for n in commented)+'.', '']
            include_sections = [s for s in sections if s.name.startswith('include ')]
            if include_sections:
                lines += ['## Includes', '']
                for s in include_sections:
                    matches = sorted(path.parent.glob(s.name[8:]))
                    links = [f'[{p.relative_to(CONFIG).as_posix()}]({link(doc,page(p))})' for p in matches if p in self.sections]
                    lines += ['- '+code(s.name[8:])+': '+(', '.join(links) or 'No matching file in this tree; this entry is not an active resolved include.')]
                lines.append('')
            detailed = [s for s in sections if s.macro or s.name.startswith('menu ') or
                        any(OPTION.match(l) and OPTION.match(l)[1] in BLOCK_KEYS for _,l in s.rows)]
            lines += ['## Macro and action index', '']
            lines += [f'- [{s.name}](#{s.anchor})' for s in detailed] or ['No macros or command templates are defined in this file.']
            lines += ['', '## Other configuration sections', '']
            others = [s for s in sections if s not in detailed and not s.name.startswith('include ')]
            lines += [f'- {code(s.name)} — [source line {s.rows[0][0]}]({link(doc,path)}#L{s.rows[0][0]}).' for s in others] or ['None.']
            lines.append('')
            for s in detailed:
                macro_count += int(s.macro)
                lines += [f'<a id="{s.anchor}"></a>', '', f'## {s.name}', '']
                short = s.name.split(' ',1)[-1]
                summary = self.annotations.get('macros',{}).get(short)
                if summary:
                    review_key = rel+'::'+s.name
                    digest = hashlib.sha256('\n'.join(l.rstrip() for _,l in s.rows).encode()).hexdigest()
                    if self.annotations.get('reviews',{}).get(review_key) != digest:
                        self.unknown.append('Review summary and lines for '+review_key+'; then set reviews digest to '+digest)
                    lines += [summary, '']
                elif s.macro:
                    description = next((l.split(':',1)[1].strip() for _,l in s.rows if l.startswith('description:')), None)
                    if description:
                        lines += [description+'.', '']
                    else:
                        self.unknown.append('Macro needs summary: '+short)
                elif s.name.startswith('menu '):
                    lines += ['LCD item: its type and enable expression below determine whether it is visible and what selecting/editing it does.', '']
                else:
                    lines += ['This configuration section supplies an event-triggered command template rather than a callable macro.', '']
                refs = self.refs('\n'.join(l for _,l in s.rows),s)
                if refs:
                    lines += ['**Calls and state references:** '+', '.join(self.ref_link(doc,n,t) for n,t in refs)+'. Conditional references are not necessarily executed.', '']
                dynamic = [k for k in self.annotations.get('dynamic_calls',{}) if any(k in l for _,l in s.rows)]
                if dynamic:
                    lines += ['**Runtime-selected calls:** '+', '.join(code(k) for k in dynamic)+'. Hook/state links above describe the known owners; external runtime values may select other commands.', '']
                lines += ['| Source line | Code | Plain explanation |', '| --- | --- | --- |']
                continuation = False
                for n,l in s.rows:
                    if not l.strip():
                        continue
                    state = 'continuation' if continuation else ''
                    # Multi-line Jinja and Python dictionary fields are one value.
                    explanation = self.explain(l,s,doc,state)
                    lines.append(f'| [{n}]({link(doc,path)}#L{n}) | {code(l.strip())} | {explanation.replace(chr(10), " ").replace("|", "&#124;")} |')
                    self.row_count += 1
                    if not l.lstrip().startswith('#'):
                        if '{%' in l and '%}' not in l: continuation = 'jinja'
                        elif continuation == 'jinja' and '%}' in l: continuation = False
                        elif continuation == 'action' and ')}' in l: continuation = False
                        elif re.match(r'^variable_.*:\s*\{',l): continuation = 'variable' if not l.rstrip().endswith('}') else False
                        elif continuation == 'variable' and l.rstrip().endswith('}'): continuation = False
                        elif '{action_' in l and ')}' not in l: continuation = 'action'
                lines.append('')
            outputs[doc] = '\n'.join(lines).rstrip()+'\n'
        printer_entries = [p for p in self.entry_points if PRINTER_ENTRY.fullmatch(p.name)]
        if printer_entries:
            expected_structure = [section.name for section in self.sections[printer_entries[0]]]
            inconsistent = [p for p in printer_entries
                            if [section.name for section in self.sections[p]] != expected_structure]
            if inconsistent:
                self.unknown.append('Printer entry-point structure differs: ' +
                                    ', '.join(p.name for p in inconsistent))
            doc = DOCS / 'printer-template.cfg.md'
            lines = [MARKER, '# printer-XX.cfg entry-point template', '',
                     'This page documents the common structure of every numbered printer entry point. '
                     'Each deployed printer keeps its own copy as `printer.cfg`; it is not a shared fleet file.', '',
                     '[All files]('+link(doc,DOCS/'README.md')+') · '
                     '[Reading guide]('+link(doc,DOCS/'READING_GUIDE.md')+')', '',
                     '## Common structure', '',
                     '- Include `machine.cfg`, which owns the shared hardware and macro configuration.',
                     '- Declare `[mcu]` and `[mcu extra_mcu]` with that printer’s USB serial identities.',
                     '- Retain Klipper’s generated `SAVE_CONFIG` block for machine-specific Eddy calibration, '
                     'PID values, input shaping, bed meshes, and other saved calibration.', '',
                     'The active section layout is checked across all numbered entry points whenever this page '
                     'is generated. Values and generated calibration are intentionally allowed to differ.', '',
                     '## Covered source files', '']
            for path in printer_entries:
                digest = hashlib.sha256(path.read_text(encoding='utf-8-sig').encode()).hexdigest()
                lines.append(f'- [{path.name}]({link(doc,path)}) — LF-normalized SHA256 `{digest}`')
            outputs[doc] = '\n'.join(lines).rstrip()+'\n'
        roots = ', '.join(code(path.relative_to(CONFIG).as_posix()) for path in self.entry_points)
        index = [MARKER, '# Fleet configuration documentation', '',
                 'Shared `.cfg`, `.conf`, and `.conf.backup` files have individual reference pages. Numbered printer entry points are condensed into one template page.', '',
                 'Resolved printer entry points: '+roots+'. Shared files are active when reachable from any of these entry points.', '',
                 '[Reading guide](READING_GUIDE.md) · [Update workflow](WORKFLOW.md)', '',
                 'These pages explain the saved candidate, including inactive files. They do not certify a successful restart or physical validation. Comments are treated as source text, never as instructions to the documentation tool.', '',
                 '## Files', '']
        printer_index_written = False
        for p in self.files:
            if PRINTER_ENTRY.fullmatch(p.name) and p.parent == CONFIG:
                if not printer_index_written:
                    names = ', '.join(path.name for path in printer_entries)
                    index.append(f'- [printer-XX.cfg entry-point template]({link(DOCS/"README.md",DOCS/"printer-template.cfg.md")}) — active; covers {names}')
                    printer_index_written = True
                continue
            index.append(f'- [{p.relative_to(CONFIG).as_posix()}]({link(DOCS/"README.md",page(p))})'+(' — active' if p in self.active else ' — separate/inactive'))
        index += ['', '## Macro lookup', '']
        for name, targets in sorted(self.targets.items()):
            for s in targets:
                index.append('- '+self.ref_link(DOCS/'README.md',name,s)+(' — delayed callback' if s.name.startswith('delayed_gcode ') else ''))
        outputs[DOCS/'README.md'] = '\n'.join(index)+'\n'
        if self.unknown:
            raise ValueError('Add reviewed explanations before generating:\n'+'\n'.join(sorted(set(self.unknown))))
        self.stats = dict(config_files=len(self.files), active_files=len(self.active), macros=macro_count,
                          explained_lines=self.row_count, generated_pages=len(outputs))
        return outputs


def run(write=False):
    builder = Builder()
    outputs = builder.build()
    stale = [p for p in DOCS.rglob('*.md') if p not in outputs and p.read_text(encoding='utf-8').startswith(MARKER)]
    different = [p for p,text in outputs.items() if not p.exists() or p.read_text(encoding='utf-8') != text]
    if write:
        for p in stale:
            if not p.resolve().is_relative_to(DOCS.resolve()):
                raise ValueError('Generated deletion escapes documentation directory')
            p.unlink()  # Only our explicitly marked generated pages, never source config.
        for p in different:
            p.parent.mkdir(parents=True,exist_ok=True)
            p.write_text(outputs[p],encoding='utf-8',newline='\n')
    elif stale or different:
        raise ValueError('Documentation is stale. Run --write and review:\n' + '\n'.join(str(p.relative_to(DOCS)) for p in stale+different))
    print(json.dumps(builder.stats,sort_keys=True))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument('--write',action='store_true')
    mode.add_argument('--check',action='store_true')
    mode.add_argument('--watch',action='store_true')
    args = parser.parse_args()
    if args.watch:
        previous = None
        print('Watching config and annotations. Ctrl+C stops. No printer connection is made.',flush=True)
        while True:
            files = config_files()+[TOOLS/'annotations.json',Path(__file__)]
            current = [(str(p),p.stat().st_mtime_ns,p.stat().st_size) for p in files]
            if current != previous:
                subprocess.run([sys.executable, str(Path(__file__).resolve()), '--write'],check=False)
                previous = current
            time.sleep(1)
    else:
        run(write=args.write)


if __name__ == '__main__':
    try: main()
    except (ValueError, OSError) as exc:
        raise SystemExit(str(exc))
